name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Install Eslint
        run: npm install eslint eslint-plugin-import prettier eslint-plugin-react-hooks --dev
      - name: Initial ESlint
        run: ./node_modules/.bin/eslint --init
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx